### ISSUE TITLE
iOS "From Messages" Auto Paste

### ISSUE THREAD

**Issue by vrockcm** [soywod/react-pin-field#28]
Hello soywood,

I think I might have found problem with the onPaste handler. 

When you receive a text message with the pin on iOS, the device usually gives you an option to auto enter it for you. Whenever I choose that option it only enters the first value into the input fields leaving other fields empty.

It works if you manually copy and paste the code in.

<img src="https://user-images.githubusercontent.com/18493432/111849082-28e54580-88e3-11eb-980e-e45e788198bf.jpg" width="30%" height="100%">

Thanks for making this awesome component

**Comment by soywod** [comment]
I bet they don't use the `onPaste` event, otherwise it would work. Or it's a special one. Which version do you use? If you have `>1.2` then you can try to inspect debug logs and see which event is triggered. It will be hard for me to debug since I don't owe an iPhone, help is welcomed!

**Comment by soywod** [comment]
In fact I was able to reproduce with `autoComplete="on"` and selecting a completion (here I selected the left completion `c'est` and I got only the `C`):

![signal-2021-03-20-105414](https://user-images.githubusercontent.com/10437171/111866048-d8b1c600-896a-11eb-91b3-d54d6196c9da.png)

It could be better if the selection acts like a paste. I will see how to do this. Thank you for the reporting!

**Comment by vrockcm** [comment]
Thank you for looking into this issue. I wish I could help but I am not that familiar with typescript.

**Comment by soywod** [comment]
It has been fixed in the v2.0.0-beta.0. The API slightly changed, I would advise to read the README and the CHANGELOG.

**Comment by mattiLeBlanc** [comment]
This issue is still current in version 3.0.15 on IOS Chrome:

https://user-images.githubusercontent.com/5285035/177256804-2570d7f3-04df-4cbe-8777-ec96e4c20bc1.mp4
